$env:AWS_SDK_LOAD_CONFIG = '1'
foreach ($secret in @("AWS_TERRAFORM_ROLE_ARN", "AWS_DEPLOY_ROLE_ARN", "TF_VAR_ALERT_EMAIL", "VITE_API_BASE_URL", "VITE_CLOUDFRONT_DOMAIN", "VITE_COGNITO_USER_POOL_ID", "VITE_COGNITO_CLIENT_ID", "SPA_BUCKET_NAME", "CLOUDFRONT_DISTRIBUTION_ID")) {
    gh secret delete $secret
}
